<a href="https://colab.research.google.com/github/edradgodoy/Clases/blob/main/Clases/IA/ejemplo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# torch libreria para la IA
import torch
# numpy Libreria para calculos matematicos
import numpy as np
# biblioteca que me permite leer desde una URL y cargarlos
import pandas as pd

# Trabajando con tensores

---



In [2]:
torch.__version__

'2.0.1+cu118'

In [3]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [4]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)

tensor([[ 1.2612e-44,  0.0000e+00],
        [-6.0539e-05,  3.1245e-41]])


tensor([[0.8880, 0.5808],
        [0.6823, 0.2185]])

In [5]:
tensor_c = torch.rand(2, 2)
tensor_c

tensor([[0.4069, 0.8506],
        [0.5905, 0.1119]])

In [6]:
result = tensor_b + tensor_c
result

tensor([[1.2949, 1.4314],
        [1.2728, 0.3304]])

In [7]:
result.shape

torch.Size([2, 2])

In [8]:
reshaped = result.view(1,4)
reshaped

tensor([[1.2949, 1.4314, 1.2728, 0.3304]])

In [9]:
points = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(points)

tensor([[1., 2.],
        [3., 4.]])


In [10]:
points[0][1]

tensor(2.)

In [11]:
points[0][1] = 2.5
points

tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])

In [12]:
points.storage()

<ipython-input-12-2c8c1a84fa09>:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 1.0
 2.5
 3.0
 4.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 4]

In [13]:
points.t()

tensor([[1.0000, 3.0000],
        [2.5000, 4.0000]])

In [14]:
tensor_x = torch.tensor([1, 2, 3, 4])
tensor_x

tensor([1, 2, 3, 4])

In [15]:
tensor_x2 = torch.unsqueeze(tensor_x, 0)
tensor_x2

tensor([[1, 2, 3, 4]])

In [16]:
tensor_x3 = torch.unsqueeze(tensor_x, 1)
tensor_x3

tensor([[1],
        [2],
        [3],
        [4]])

In [17]:
numpyArray = np.random.randn(2,2)
torch.from_numpy(numpyArray)

tensor([[ 0.8025, -0.4955],
        [ 0.1223,  0.2335]], dtype=torch.float64)

# Representar datos con tensores

---



In [18]:
from_numpy = torch.from_numpy(numpyArray)
print(from_numpy)
# sacamos la media del array = tensor
print(torch.mean(from_numpy))
#calculamos la media por dimenciones
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([[ 0.8025, -0.4955],
        [ 0.1223,  0.2335]], dtype=torch.float64)
tensor(0.1657, dtype=torch.float64)
tensor([ 0.4624, -0.1310], dtype=torch.float64)
tensor([0.1535, 0.1779], dtype=torch.float64)


In [19]:
# calculamos la desviacion estandar
print(torch.std(from_numpy))
print(torch.std(from_numpy, dim=0))

tensor(0.5320, dtype=torch.float64)
tensor([0.4810, 0.5155], dtype=torch.float64)


# La desviación estándar o típica mide la dispersión de los valores en torno a la media de dichos valores. En otras palabras, determina cuánto difieren los valores entre sí.

1. Al realizar encuestas que contengan puntuaciones o valores numéricos, la desviación estándar sirve para entender cuánta variedad hay en las respuestas dadas por los encuestados.
2. Para determinar el tiempo meteorológico, la desviación estándar se utiliza para prever hasta cierto punto qué temperatura habrá en un día concreto, basado en los datos recopilados en los años previos.
3. Dentro del negocio de los bienes raíces o bienes inmuebles, este tipo de desviación sirve para conocer la variedad de precios de las casas que hay en un barrio, pueblo o ciudad.
4. La desviación estándar se utiliza para conocer la variedad en edades de las personas que asisten a un evento o conferencia, o de clientes que compran un producto determinado.
5. En el mercado de inversiones, la desviación estándar es uno de los factores claves de cara a conocer el riesgo de inversión y la variación en posibles ganancias.


---





In [20]:
#guardamos los resultados en un archivo
torch.save(from_numpy, 'tensor.t')

In [21]:
load = torch.load('tensor.t')
load

tensor([[ 0.8025, -0.4955],
        [ 0.1223,  0.2335]], dtype=torch.float64)

In [22]:
# leer y cargar datos por URL
## Define path data
COLUMNS = ['age','workclass', 'fnlwgt', 'education', 'education_num', 'marital',
           'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss',
           'hours_week', 'native_country', 'label']
PATH = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
dataframe = pd.read_csv(PATH,
                       skipinitialspace=True,
                       names = COLUMNS,
                       index_col=False)
dataframe

age         workclass  fnlwgt   education  education_num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

                  marital         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital_gain  capital_loss  hours_week native_country  label  
0              2174             0          40  United-States  <=50K  
1                 0             0          13  United-States  <=50K  
2                 0             0          40  United-States  <=50K  
3                 0             0          40  United-States  <=50K  
4                 0             0          40           Cuba  <=50K  
...             ...           ...         ...            ...    ...  
32556             0             0          38  United-States  <=50K  
32557             0             0          40  United-States   >50K  
32558             0             0          40  United-States  <=50K  
32559             0             0          20  United-States  <=50K  
32560         15024             0          40  United-States   >50K  

[32561 rows x 15 columns]

In [23]:
dataframe.shape

(32561, 15)

In [24]:
dataframe.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital',
       'occupation', 'relationship', 'race', 'sex', 'capital_gain',
       'capital_loss', 'hours_week', 'native_country', 'label'],
      dtype='object')

In [25]:
subset = dataframe[['age', 'education_num', 'hours_week']]
subset

age  education_num  hours_week
0       39             13          40
1       50             13          13
2       38              9          40
3       53              7          40
4       28             13          40
...    ...            ...         ...
32556   27             12          38
32557   40              9          40
32558   58              9          40
32559   22              9          20
32560   52              9          40

[32561 rows x 3 columns]

In [26]:
columns = subset.columns[1:]
datos = torch.tensor(subset.values).float()
datos.shape, datos.type()

(torch.Size([32561, 3]), 'torch.FloatTensor')

In [27]:
data = datos[:, 1:]
data, data.shape

(tensor([[13., 40.],
         [13., 13.],
         [ 9., 40.],
         ...,
         [ 9., 40.],
         [ 9., 20.],
         [ 9., 40.]]),
 torch.Size([32561, 2]))

In [28]:
target = datos[:,0]
target

tensor([39., 50., 38.,  ..., 58., 22., 52.])

In [29]:
Media = torch.mean(data, dim=0)
Media

tensor([10.0807, 40.4375])

In [30]:
Buenos = data[torch.ge(target, 85)]
Promedio = data[torch.gt(target, 70) & torch.gt(target, 70)]
Bajo = data[torch.le(target, 70)]

buenosMean = torch.mean(Buenos, dim=0)
promedioMean = torch.mean(Promedio, dim=0)
BajoMean = torch.mean(Bajo, dim=0)

buenosMean, promedioMean, BajoMean

(tensor([10.1765, 35.9412]),
 tensor([ 9.2926, 26.6778]),
 tensor([10.0940, 40.6695]))